-- MySQL Script generated by MySQL Workbench
-- Sat Oct 14 21:57:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wwsishop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wwsishop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wwsishop` DEFAULT CHARACTER SET utf8 ;
USE `wwsishop` ;

-- -----------------------------------------------------
-- Table `wwsishop`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`Customer` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`Customer` (
  `IdCustomer` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `PasswordHash` VARCHAR(128) NOT NULL,
  `BirthDate` DATE NULL,
  PRIMARY KEY (`IdCustomer`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`Product` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`Product` (
  `IdProduct` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NOT NULL,
  `Description` TEXT NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `SKU` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`Address` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`Address` (
  `IdAddress` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Mobile` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Province` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `BuildingNumber` VARCHAR(45) NOT NULL,
  `PostalCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`Order` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`Order` (
  `IdOrder` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdCustomer` BIGINT UNSIGNED NOT NULL,
  `IdShippingAddress` BIGINT UNSIGNED NOT NULL,
  `OrderNumber` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdOrder`),
  INDEX `fk_Order_Customer_idx` (`IdCustomer` ASC) VISIBLE,
  INDEX `fk_Order_Address1_idx` (`IdShippingAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer`
    FOREIGN KEY (`IdCustomer`)
    REFERENCES `wwsishop`.`Customer` (`IdCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Address1`
    FOREIGN KEY (`IdShippingAddress`)
    REFERENCES `wwsishop`.`Address` (`IdAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`OrderItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`OrderItem` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`OrderItem` (
  `IdOrderItem` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdOrder` BIGINT UNSIGNED NOT NULL,
  `IdProduct` BIGINT UNSIGNED NOT NULL,
  `SKU` VARCHAR(100) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Quantity` INT UNSIGNED NOT NULL,
  `Discount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`IdOrderItem`),
  INDEX `fk_OrderItem_Order1_idx` (`IdOrder` ASC) VISIBLE,
  INDEX `fk_OrderItem_Product1_idx` (`IdProduct` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`IdOrder`)
    REFERENCES `wwsishop`.`Order` (`IdOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Product1`
    FOREIGN KEY (`IdProduct`)
    REFERENCES `wwsishop`.`Product` (`IdProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`CustomerAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`CustomerAddress` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`CustomerAddress` (
  `IdCustomer` BIGINT UNSIGNED NOT NULL,
  `IdAddress` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdCustomer`, `IdAddress`),
  INDEX `fk_CustomerAddress_Address1_idx` (`IdAddress` ASC) VISIBLE,
  CONSTRAINT `fk_CustomerAddress_Customer1`
    FOREIGN KEY (`IdCustomer`)
    REFERENCES `wwsishop`.`Customer` (`IdCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerAddress_Address1`
    FOREIGN KEY (`IdAddress`)
    REFERENCES `wwsishop`.`Address` (`IdAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`Category` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`Category` (
  `IdCategory` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ParentIdCategory` INT UNSIGNED NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` TEXT NOT NULL,
  PRIMARY KEY (`IdCategory`),
  INDEX `fk_Category_Category1_idx` (`ParentIdCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Category_Category1`
    FOREIGN KEY (`ParentIdCategory`)
    REFERENCES `wwsishop`.`Category` (`IdCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`ProductCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`ProductCategory` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`ProductCategory` (
  `IdCategory` INT UNSIGNED NOT NULL,
  `IdProduct` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdCategory`, `IdProduct`),
  INDEX `fk_ProductCategory_Category1_idx` (`IdCategory` ASC) VISIBLE,
  CONSTRAINT `fk_ProductCategory_Product1`
    FOREIGN KEY (`IdProduct`)
    REFERENCES `wwsishop`.`Product` (`IdProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductCategory_Category1`
    FOREIGN KEY (`IdCategory`)
    REFERENCES `wwsishop`.`Category` (`IdCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`Cart` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`Cart` (
  `IdCart` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdCustomer` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdCart`),
  INDEX `fk_Cart_Customer1_idx` (`IdCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_Customer1`
    FOREIGN KEY (`IdCustomer`)
    REFERENCES `wwsishop`.`Customer` (`IdCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`CartItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`CartItem` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`CartItem` (
  `IdCartItem` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdCart` BIGINT UNSIGNED NOT NULL,
  `IdProduct` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdCartItem`),
  INDEX `fk_CartItem_Cart1_idx` (`IdCart` ASC) VISIBLE,
  INDEX `fk_CartItem_Product1_idx` (`IdProduct` ASC) VISIBLE,
  CONSTRAINT `fk_CartItem_Cart1`
    FOREIGN KEY (`IdCart`)
    REFERENCES `wwsishop`.`Cart` (`IdCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartItem_Product1`
    FOREIGN KEY (`IdProduct`)
    REFERENCES `wwsishop`.`Product` (`IdProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`Invoice` (
  `IdInvoice` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdCustomer` BIGINT UNSIGNED NOT NULL,
  `Number` VARCHAR(100) NOT NULL,
  `IssueDate` DATE NOT NULL,
  `PaymentDate` DATE NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Discount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`IdInvoice`),
  INDEX `fk_Invoice_Customer1_idx` (`IdCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Invoice_Customer1`
    FOREIGN KEY (`IdCustomer`)
    REFERENCES `wwsishop`.`Customer` (`IdCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`InvoiceItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`InvoiceItem` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`InvoiceItem` (
  `IdOrder` BIGINT UNSIGNED NOT NULL,
  `IdInvoice` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdOrder`, `IdInvoice`),
  INDEX `fk_InvoiceItem_Invoice1_idx` (`IdInvoice` ASC) VISIBLE,
  CONSTRAINT `fk_InvoiceItem_Order1`
    FOREIGN KEY (`IdOrder`)
    REFERENCES `wwsishop`.`Order` (`IdOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InvoiceItem_Invoice1`
    FOREIGN KEY (`IdInvoice`)
    REFERENCES `wwsishop`.`Invoice` (`IdInvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wwsishop`.`ProductReview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwsishop`.`ProductReview` ;

CREATE TABLE IF NOT EXISTS `wwsishop`.`ProductReview` (
  `IdProductReview` BIGINT NOT NULL,
  `IdProduct` BIGINT UNSIGNED NOT NULL,
  `Description` TEXT NOT NULL,
  `Rating` SMALLINT(6) NOT NULL,
  `ReviewDate` DATE NOT NULL,
  PRIMARY KEY (`IdProductReview`),
  INDEX `fk_ProductReview_Product1_idx` (`IdProduct` ASC) VISIBLE,
  CONSTRAINT `fk_ProductReview_Product1`
    FOREIGN KEY (`IdProduct`)
    REFERENCES `wwsishop`.`Product` (`IdProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
